name: Continuous Integration
on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches: [main]
jobs:
  test:
    name: Build and Test
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 1
          persist-credentials: true
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: '6.x'
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Nuget restore winget-cli
        run: nuget restore
        working-directory: winget-cli/src
      - name: Build winget-cli
        run: msbuild.exe /p:Configuration=Release
        working-directory: winget-cli/src
      - name: .NET Restore
        run: dotnet restore
      # dotnet build not supported see https://github.com/microsoft/microsoft-ui-xaml/issues/5327
      - name: .NET Build
        run: msbuild.exe /p:Configuration=Release
      - name: .NET Test
        run: dotnet test --configuration Release --collect:"XPlat Code Coverage"  --logger "GitHubActions"
      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: Code coverage
          path: "**/coverage.cobertura.xml"
